apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  selector:
    matchLabels:
      app: user-management
  replicas: 1
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: registry.cn-hangzhou.aliyuncs.com/pipipan/user-management:{{ .Values.imageVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8100
          env:
            - name: EUREKA_SERVICE_URI
              value: {{ .Values.eurekaURI}}
            - name: MONGO_URI
              value: {{ .Values.mongoURI }}
            - name: ZIPKIN_URI
              value: {{ .Values.zipkinURI }}
