apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: registry.cn-hangzhou.aliyuncs.com/pipipan/gateway:{{ .Values.imageVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: EUREKA_SERVICE_URI
              value: {{ .Values.eurekaURI }}
